name: Artifact

on: [push]

env:
 ARTIFACT_NAME: myartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Upload the artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: .
          
